lzc-sdk-version: '0.1'
name: 轮回勇者传说
package: shiina.lzcapp.idlegame
version: 1.3.3
application:
  routes:
    - /=http://idle-game.shiina.lzcapp.idlegame.lzcapp:80
  subdomain: idle-game
  ingress:
    - protocol: tcp
      port: 80
      service: idle-game
services:
  idle-game:
    image: registry.lazycat.cloud/u12914963/dockerhub02347/idlegame:52e2679b4f4f8bde
    ports:
      - 80