lzc-sdk-version: '0.1'
name: chinesebqb
package: shiina.lzcapp.chinesebqb
version: 1.0.0
application:
  routes:
    - /=http://chinesebqb.shiina.lzcapp.chinesebqb.lzcapp:3000
  subdomain: chinesebqb
services:
  chinesebqb:
    image: registry.lazycat.cloud/u12914963/dockerhub02347/chinesebqb:34440ebbf8c19145
    ports:
      - 3000
