lzc-sdk-version: '0.1'
name: 我的世界-龙之冒险
package: shiina.lzcapp.minecraftdragonadventure
version: 1.0.0
application:
  routes:
    - /=http://dragonadventure.shiina.lzcapp.minecraftdragonadventure.lzcapp:3000
  subdomain: dragonadventure
  ingress:
    - protocol: tcp
      port: 25565
      service: dragonadventure
services:
  dragonadventure:
    image: registry.lazycat.cloud/u12914963/dockerhub02347/minecraftdragonadventure:0770949b372287bc
    binds:
      - /lzcapp/var/data:/app/data
    ports:
      - 25565:25565
      - 3000:3000
    setup_script: |
      mkdir -p /app/data
      if [ ! -f /app/data/run.sh ]; then
        cp -r /app/server/* /app/data/
      fi