lzc-sdk-version: '0.1'
name: Ward 服务器状态监控
package: shiina.lzcapp.ward
version: 2.5.2
application:
  routes:
    - /=http://ward.shiina.lzcapp.ward.lzcapp:4000
  subdomain: ward
services:
  ward:
    image: registry.lazycat.cloud/u12914963/antonyleons/ward:0415c64d6d814dbc
    ports:
      - 4000
    environment:
      - WARD_PORT=4000
      - WARD_THEME=light
    privileged: true