lzc-sdk-version: '0.1'
name: Redis
package: shiina.lzcapp.redis
version: 1.0.0
application:
  background_task: true
  routes:
    - /=http://redis.shiina.lzcapp.redis.lzcapp:6379
  subdomain: redis
  ingress:
    - protocol: tcp
      port: 6379
      service: redis
services:
  redis:
    image: registry.lazycat.cloud/u12914963/library/redis:7f346df9cd82ade3
    container_name: redis
    ports:
      - 6379:6379
    binds:
      - /lzcapp/var/redis-data:/data